export const USER_REQUEST = "USER_REQUEST";
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_FAILURE_REQUEST = "USER_FAILURE_REQUEST";
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
