export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_FAILURE = "PRODUCT_FAILURE";
export const PRODUCT_SUCCESS = " PRODUCT_SUCCESS";

export const ADDTOCART_REQUEST = "ADDTOCART_REQUEST";
export const ADDTOCART_FAILURE = "ADDTOCART_FAILURE";
export const ADDTOCART_SUCCESS = " ADDTOCART_SUCCESS";
